//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "algoritmos")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub nombre: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::estadisticas::Entity")]
    Estadisticas,
}

impl Related<super::estadisticas::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Estadisticas.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
