//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "estadisticas")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub algoritmo_id: i32,
    pub tiempo: i64,
    pub comparaciones: i64,
    pub intercambios: i64,
    pub escrituras: i64,
    pub cantidad_datos: i32,
    pub fecha: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::algoritmos::Entity",
        from = "Column::AlgoritmoId",
        to = "super::algoritmos::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Algoritmos,
}

impl Related<super::algoritmos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Algoritmos.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
